### ISSUE TITLE
Using "TOPIC" throws exception

### ISSUE THREAD

**Issue by fritzwf** [riftninja/google-news-api#2]
**Command:**
```
var news = require('google-news-json');
news.getNews(news.TOPIC, "apple", "en-US", (err, response) => {
   console.log(JSON.stringify(response, null, 2));
});
```

**Error:**
```
Error: Invalid character in entity name
Line: 0
Column: 10747
Char: &
    at error (C:\Dev\jsTest\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Dev\jsTest\node_modules\sax\lib\sax.js:677:7)
    at SAXParser.write (C:\Dev\jsTest\node_modules\sax\lib\sax.js:1491:13)
    at Parser.exports.Parser.Parser.parseString (C:\Dev\jsTest\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (C:\Dev\jsTest\node_modules\xml2js\lib\parser.js:5:59)
    at C:\Dev\jsTest\node_modules\rss-to-json\dist\index.js:1:1314
    at process._tickCallback (internal/process/next_tick.js:68:7)
null
(node:1908) UnhandledPromiseRejectionWarning: Error: Invalid character in entity name
Line: 0
Column: 10747
Char: &
    at error (C:\Dev\jsTest\node_modules\sax\lib\sax.js:651:10)
    at strictFail (C:\Dev\jsTest\node_modules\sax\lib\sax.js:677:7)
    at SAXParser.write (C:\Dev\jsTest\node_modules\sax\lib\sax.js:1491:13)
    at Parser.exports.Parser.Parser.parseString (C:\Dev\jsTest\node_modules\xml2js\lib\parser.js:323:31)
    at Parser.parseString (C:\Dev\jsTest\node_modules\xml2js\lib\parser.js:5:59)
    at C:\Dev\jsTest\node_modules\rss-to-json\dist\index.js:1:1314
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block
, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node
.js process with a non-zero exit code.
```

**Comment by riftninja** [comment]
@fritzwf please confirm if this has been fixed in 2.x.x. Also updated [readme](https://github.com/riftninja/google-news-api/blob/master/README.md) to include supported `topics`
